/* empty css                      */import{a as q,S as P,i as n}from"./assets/vendor-C1DvvBV_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const $="https://pixabay.com/api/",M="57664861-998876c815f7f33043a4b1ff1";async function p(s,t){return(await q.get($,{params:{key:M,q:s,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const f=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".load-more"),R=new P(".gallery a",{captionsData:"alt",captionDelay:250});function y(s){const t=s.map(({webformatURL:r,largeImageURL:c,tags:e,likes:o,views:i,comments:S,downloads:v})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${c}">
            <img class="gallery-image" src="${r}" alt="${e}" loading="lazy" />
            <div class="gallery-info">
              <p><b>Likes</b><span>${o}</span></p>
              <p><b>Views</b><span>${i}</span></p>
              <p><b>Comments</b><span>${S}</span></p>
              <p><b>Downloads</b><span>${v}</span></p>
            </div>
          </a>
        </li>
      `).join("");f.insertAdjacentHTML("beforeend",t),R.refresh()}function B(){f.innerHTML=""}function m(){g.classList.remove("is-hidden")}function L(){g.classList.add("is-hidden")}function l(){h.classList.remove("is-hidden")}function b(){h.classList.add("is-hidden")}const u=document.querySelector(".form"),O=u.elements["search-text"],x=document.querySelector(".load-more"),H=document.querySelector(".gallery"),w=15;let d="",a=1;u.addEventListener("submit",I);x.addEventListener("click",A);async function I(s){s.preventDefault();const t=O.value.trim();if(!t){n.warning({message:"Please enter a search query",position:"topRight"});return}d=t,a=1,B(),b(),m();try{const r=await p(d,a);if(!r.hits.length){n.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}if(y(r.hits),u.reset(),r.totalHits<=a*w){n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}l()}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}}async function A(){a+=1,b(),m();try{const s=await p(d,a);y(s.hits),s.totalHits<=a*w?n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):l();const t=H.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}catch{a-=1,n.error({message:"Something went wrong. Please try again later.",position:"topRight"}),l()}finally{L()}}
//# sourceMappingURL=index.js.map
